In [1]:
import geopandas as gpd

In [13]:
def readfile(x,y):
    al = gpd.read_file(x)
    place = gpd.read_file(y).to_crs(al.crs)
    return al, place

In [24]:
al, place = readfile("C:/Users/thewe/OneDrive/Desktop/College/AES408/files/cb_2024_01_place_500k", "C:/Users/thewe/OneDrive/Desktop/College/AES408/files/ne_10m_populated_places")

In [17]:
al.head()

,STATEFP,PLACEFP,PLACENS,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,01,32704,02403782,1600000US0132704,0132704,Haleyville,Haleyville city,AL,Alabama,25,21713018,130983,"MULTIPOLYGON (((-87.60417 34.24614, -87.60201 ..."
1,01,45472,02406131,1600000US0145472,0145472,McIntosh,McIntosh town,AL,Alabama,43,2579767,0,"POLYGON ((-88.03726 31.27171, -88.03112 31.271..."
2,01,53784,02406982,1600000US0153784,0153784,Newbern,Newbern town,AL,Alabama,43,3010370,6872,"POLYGON ((-87.54125 32.60104, -87.52531 32.601..."
3,01,78204,02405634,1600000US0178204,0178204,Valley,Valley city,AL,Alabama,25,33384157,0,"MULTIPOLYGON (((-85.17006 32.7799, -85.17005 3..."
4,01,02836,02405172,1600000US0102836,0102836,Ashford,Ashford city,AL,Alabama,25,16064130,56699,"POLYGON ((-85.25721 31.17963, -85.25643 31.204..."

In [18]:
place.head()

,SCALERANK,NATSCALE,LABELRANK,FEATURECLA,NAME,NAMEPAR,NAMEALT,NAMEASCII,ADM0CAP,CAPIN,...,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,FCLASS_TLC,geometry
0,10,1,8.0,Admin-1 capital,Colonia del Sacramento,NaN,NaN,Colonia del Sacramento,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-57.83612 -34.46979)
1,10,1,8.0,Admin-1 capital,Trinidad,NaN,NaN,Trinidad,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.901 -33.544)
2,10,1,8.0,Admin-1 capital,Fray Bentos,NaN,NaN,Fray Bentos,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-58.304 -33.139)
3,10,1,8.0,Admin-1 capital,Canelones,NaN,NaN,Canelones,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.284 -34.538)
4,10,1,8.0,Admin-1 capital,Florida,NaN,NaN,Florida,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.215 -34.099)

In [19]:
al_place = gpd.sjoin(al, place)

In [21]:
al_place

,STATEFP,PLACEFP,PLACENS,GEOIDFQ,GEOID,NAME_left,NAMELSAD,STUSPS,STATE_NAME,LSAD,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,FCLASS_TLC
16,01,50000,02404278,1600000US0150000,0150000,Mobile,Mobile city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,01,51000,02404289,1600000US0151000,0151000,Montgomery,Montgomery city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,01,26896,02403619,1600000US0126896,0126896,Florence,Florence city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,01,28696,02403673,1600000US0128696,0128696,Gadsden,Gadsden city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,01,21184,02404238,1600000US0121184,0121184,Dothan,Dothan city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,01,07000,02403868,1600000US0107000,0107000,Birmingham,Birmingham city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,01,69120,02405441,1600000US0169120,0169120,Selma,Selma city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,01,03076,02403132,1600000US0103076,0103076,Auburn,Auburn city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382,01,24184,02403567,1600000US0124184,0124184,Enterprise,Enterprise city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,01,77256,02405614,1600000US0177256,0177256,Tuscaloosa,Tuscaloosa city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,01,37000,02404746,1600000US0137000,0137000,Huntsville,Huntsville city,AL,Alabama,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN